### ISSUE TITLE
Better performance?

### ISSUE THREAD

**Issue by danqing** [sdispater/pendulum#147]
Performance may not be a goal of pendulum, but I happen to run into this post: https://aboutsimon.com/blog/2016/08/04/datetime-vs-Arrow-vs-Pendulum-vs-Delorean-vs-udatetime.html and it looks like pendulum is the slowest among popular python datetime libraries. Is there any plan to speed it up?

Thanks!

**Comment by sdispater** [comment]
Hi,

The article you mention dates back to August 2016 when Pendulum was still pretty young. A lot of performance improvements has been made since then :-)

You can see some benchmark results of my own here: https://pendulum.eustace.io/faq/

Also, Pendulum now has a fast ISO 8601/RFC 3339 parser (even faster than udatetime):

```python
>>> from pendulum.helpers import parse_iso8601
>>> from udatetime import from_string
>>> %timeit parse_iso8601('2017-06-08T12:34:56.123456+01:30')
1000000 loops, best of 3: 583 ns per loop
>>> from_string('2017-06-08T12:34:56.123456+01:30')
100000 loops, best of 3: 1.83 µs per loop
```

So, I think you're pretty safe with Pendulum :-)

**Comment by danqing** [comment]
Thanks & closing this :)

**Comment by PanCakeConnaisseur** [comment]
How does modern Pendulum compare to the built-in datetime in Pyhon 3.11 performance-wise? The [FAQ](https://pendulum.eustace.io/faq/) only compares to other librarires,

**Comment by olk-m** [comment]
> How does modern Pendulum compare to the built-in datetime in modern Python (~3.11) performance-wise? The [FAQ](https://pendulum.eustace.io/faq/) only compares to other libraries.

@PanCakeConnaisseur You can see in https://github.com/olk-m/benchmark-datetime
