### ISSUE TITLE
Period length calculation problem

### ISSUE THREAD

**Issue by dekoza** [sdispater/pendulum#178]
I discovered something odd when experimenting with period length calculations around DST change time. Please consider this example:

```python
tz = pendulum.timezone('America/Los_Angeles')
start_time = pendulum.parse('2018-03-11 09:00:00+00:00')
end_time = pendulum.parse('2018-03-11 10:00:00+00:00')
print((end_time - start_time).hours)     # 1
print((end_time.in_tz(tz) - start_time).hours)  # 1
print((end_time - start_time.in_tz(tz)).hours)  # 1
print((end_time.in_tz(tz) - start_time.in_tz(tz)).hours)  # 2 ?!

p1 = end_time - start_time
print(start_time + p1 == end_time)   # True
print(p1.total_hours())  # 1.0

p2 = end_time.in_tz(tz) - start_time.in_tz(tz)
print(start_time + p2 == end_time)  # False
print(p2.total_hours())  # 1.0

```

**Comment by sdispater** [comment]
Thanks for reporting this!

Yes, there is definitely something wrong here.

I will take a look and get back to you.

**Comment by pganssle** [comment]
I don't think there's anything wrong here. If you use `total_hours()` you'll get the behavior you expect.

The problem is that in the `America/Los_Angeles` time zone, there are **2** wall hours between those two UTC times. The first example you're subtracting two times both in UTC, so there's both 1 wall hour and 1 actual hour.

In the next two examples, you have "mixed zone" subtractions, so "wall time" doesn't make a lot of sense, so it's very intuitive to me that if you allow these operations to exist, you'd return the total elapsed amount of time between them.

In the final example, both are in the same "wall time" and you can actually see that one of them is `3:00` and the other one is `01:00`, so there are 2 "wall hours" between them (even though only one actually existed).

This is somewhat counter-intuitive on short timescales, but I find these dynamics much less counter-intuitive on the time scale of days and hours. For example noon the day *before* a transition is "1 day" before noon the day *after* a transition, even though the actual elapsed time is either 23 or 25 hours.

I think the "same zone" and "between zone" dynamics are similar to what I wrote about [in this blog post](https://blog.ganssle.io/articles/2018/02/a-curious-case-datetimes.html) (though in that case I think the result is somewhat absurd, whereas in this case I understand why it makes sense).

**Comment by dekoza** [comment]
The difference between two `Pendulum` instances is a `Period` instance which is a subclass of `timedelta`. I expect it to be neutral and timezone-agnostic. It should not care if the instances it was calculated from were UTC or in any timezone. Who cares about "wall time" anyway? If you rent a car at the LA airport at 0:30 on March 11th 2018 and release it at 5:00 March 11th 2018, how much should you be charged for the service (let's say they charge per minute)? 

```tz = pendulum.timezone('America/Los_Angeles')
p1 = pendulum.parse('2018-03-11 00:30:00', tz=tz)
p2 = pendulum.parse('2018-03-11 05:00:00', tz=tz)
d = p2 - p1

print(d.hours)  # 4
print(d.in_hours())  # 3
print(d.total_hours())  # 3.5

d2 = p2.in_tz('utc') - p1.in_tz('utc')

print(d2.hours)  # 3
print(d2.in_hours()  # 3
print(d2.total_hours())  # 3.5

print(d2 == d1)  # True ?!
```

**Comment by pganssle** [comment]
@dekoza I don't know much about `pendulum.Period`, but from what it looks like from the REPL it stores the beginning and ending times of the period, so it's more akin to `(start_time, time_delta)` than to `(time_delta)` alone (though it does seem to contain the beginning and ending time zones as well.

In any case, the question of what "neutral and timezone agnostic" means really only moves the problem back to be resolved at the point of subtraction, it doesn't resolve anything.

The reason you care about "wall time" is because if you have a meeting today at noon, and then 2 days after that, you expect the second meeting to *also* be at noon, but if *all* datetime arithmetic is just "elapsed time", then "2 days from noon" will sometimes be a time at 11 or sometimes at 13, or sometimes at 11:45 or something, depending on your time zone.

Generally I just recommend that if you want absolute time elapsed, do your subtractions in UTC where this will never be a problem. The only reason you're even working with non-UTC zones is because sometimes you actually *need* wall clock arithmetic.

**Comment by pganssle** [comment]
I think basically the problem with this, as with many other datetime related things, is that depending on the context of the question you are asking, there are two "obvious" things to do, and those two obvious things are in opposition.

**Comment by dekoza** [comment]
@pganssle you are wrong. There are ways to "add two days" to a timezoned timestamp so that it crosses DST change correctly so that noon stays noon. I just want to have correct Period instances regardless of the timezone my initial timestamps are in. It's not rocket science.

Now if you excuse me I'd like to focus on something productive, like - I don't know - actually writing a patch to prove my point.

**Comment by pganssle** [comment]
@dekoza I'm saying the semantics are inherently unclear, and you have to resolve them one way or the other. If you want to maintain compatibility with `datetime`'s arithmetic semantics, you'll have this particular feature.

In any case, the problem isn't to "add two days" to a timezoned timestamp such that it crosses DST correctly - the current `datetime` and `timedelta` semantics already do that correctly (as does the subtraction). Subtraction, however, is the conjugate of addition, so it would be strange to be able to specify a `dt` which does not satisfy this condition:

```python
td = timedelta(days=2)
dt_end = dt + td
assert (dt_end - dt) == td
```

Mind you, with the *current* mechanism of addition and subtraction, you have this property *and* you have the ability to get "elapsed time" arithmetic by simply converting to UTC before any operation. If you redefine arithmetic such that *all* operations effectively operate on UTC datetimes, you lose the ability to do wall-time math (which would be very counter-intuitive in many peoples' use cases).

**Comment by sdispater** [comment]
@pganssle 

The idea is we should always have:

```python
dt_end = dt + (dt_end - dt)
```

which Pendulum actually does right when adding/subtracting units of variable length (like days):

```python
>>> import pendulum
>>> dt = pendulum.create(2018, 3, 11, 0, 30, tz='America/Los_Angeles')
>>> dt_end = pendulum.create(2018, 3, 12, 0, 30, tz='America/Los_Angeles')
>>> dt_end == dt + (dt_end - dt)
True 
```

but not for other units:

```python
>>> dt = pendulum.create(2018, 3, 11, 0, 30, tz='America/Los_Angeles')
>>> dt_end = pendulum.create(2018, 3, 12, 3, 30, tz='America/Los_Angeles')
>>> dt_end == dt + (dt_end - dt)
False
```

This is more or less what this issue is about.

And the thing is the standard library does not get this right:

```python
>>> from datetime import datetime, timedelta
>>> from dateutil.tz import gettz
>>> dt = datetime(2018, 3, 11, 0, 30, tzinfo=gettz('America/Los_Angeles'))
>>> dt_end = datetime(2018, 3, 12, 0, 30, tzinfo=gettz('America/Los_Angeles'))
>>> dt_end == dt + (dt_end - dt)
False
>>> dt_end - dt
datetime.timedelta(0, 82800) 
# This is actually correct (23 hours) but it's also a full day
# however there is no way to handle that in the standard library
>>> dt_end = datetime(2018, 3, 11, 3, 30, tzinfo=gettz('America/Los_Angeles'))
>>> dt_end == dt + (dt_end - dt)
False
>>> dt_end - dt
datetime.timedelta(0, 7200)  # But only one hour has passed
```

**Comment by dekoza** [comment]
It looks like the `precise_diff` is the culprit. Despite the name it does not calculate the precise difference between two datetimes. At least not in my understanding of the term 😉 For me the difference between two datetimes is the exact amount of (femto)seconds that passed between those points in the Continuum. It really has nothing to do with the clock.

**Comment by sdispater** [comment]
@dekoza Yes, you're right, `precise_diff()` was the culprit :-)

If both datetimes were in the same timezone, it would not use the offsets to get the proper time difference. But this is only true for variable-length units (year, month, day).

Commit 5b06241 should fix the issue.

It will land in the next bugfix release.

**Comment by dekoza** [comment]
Marvelous! Thank you, @sdispater

**Comment by pganssle** [comment]
@sdispater Actually, you've been fooled by the same issue I mentioned in my blog post. This is essentially an implementation detail in `dateutil` that `tz.gettz('America/Los_Angeles')` returns a new instance every time you call it. I plan to add caching at some point soon so this will no longer be an issue. The reason this is an issue is that the standard library uses object identity for determining which addition semantics to use. When you make them all use the same zone, you can see what I'm talking about:

```python
>>> from datetime import datetime, timedelta
>>> from dateutil.tz import gettz
>>> LA = gettz('America/Los_Angeles')
>>> dt = datetime(2018, 3, 11, 0, 30, tzinfo=LA)
>>> dt_end = datetime(2018, 3, 12, 0, 30, tzinfo=LA)
>>> print(dt_end == dt + (dt_end - dt))
True
>>> print(dt_end - dt)
1 day, 0:00:00
>>> dt_end = datetime(2018, 3, 11, 3, 30, tzinfo=LA)
>>> print(dt_end - dt)
3:00:00
```

So like I said, it's pretty consistent in the standard library. You're free to use whatever semantics you want, but I think you'll find that people find it somewhat counter-intuitive that they always get absolute elapsed time (or that adding `timedelta(day=1)` to some value always adds exactly 24 hours. It's particularly unfortunate because IIRC pendulum doesn't have a notion of naive datetimes, so if all arithmetic is elapsed time arithmetic, I'm not quite sure how you express wall time arithmetic.

**Comment by sdispater** [comment]
@pganssle 

My mistake I thought `gettz()` returned the same `tzinfo` object.

But still, your examples seem counter-intuitive to me:

```python
>>> from datetime import datetime, timedelta
>>> from dateutil.tz import gettz
>>> LA = gettz('America/Los_Angeles')
>>> dt = datetime(2018, 3, 11, 0, 30, tzinfo=LA)
>>> dt_end = datetime(2018, 3, 12, 0, 30, tzinfo=LA)
>>> print(dt_end - dt)
'1 day, 0:00:00'
```

This one is actually right but you lose the information that it's also 23 hours. I know you can get the 23 hours by going trough UTC but that's far from being intuitive.

```python
>>> dt_end = datetime(2018, 3, 11, 3, 30, tzinfo=LA)
>>> print(dt_end -dt)
'3:00:00'
```

This is actually wrong, only 2 hours have passed in the `America/Los_Angeles` timezone not 3.

And this is where I wanted Pendulum to be right:

```python
>>> import pendulum
>>> dt = pendulum.create(2018, 3, 11, 0, 30, tz='America/Los_Angeles')
>>> dt_end = pendulum.create(2018, 3, 12, 0, 30, tz='America/Los_Angeles')
>>> (dt_end - dt).in_days()
1
>>> (dt_end - dt).in_hours()
23
>>> dt_end = pendulum.create(2018, 3, 11, 3, 30, tz='America/Los_Angeles')
>>> (dt_end - dt).in_hours()
2
```

**Comment by pganssle** [comment]
@sdispater It's not about wrong or right here, it's a choice between two equally valid conceptions of the semantics. If you say "add 3 hours to midnight", you get 3AM because you've advanced the clock 3 hours. If you say "start at midnight and jump to the time after which 3 real-time hours have elapsed", you will end up at 4AM, not 3AM in this case.

The reason I bring up the "1 day" case is that there's no "right" intuition that covers all the cases, because generally on the scale of 1 day you tend to be doing operations where you want wall clock offsets, whereas offsets of around 1-2 hours, you tend to be thinking about elapsed time so your intuition tends to prefer absolute elapsed time.

One major problem in designing an API around this is that I can't think of a way that would be "obvious" here other than simply disallowing arithmetical operations entirely since they are overloaded and encoding the semantics you want into the operator itself, but that would be cumbersome and that ship has sailed long ago.

If you want `pendulum` to continue to be a (drop in) `datetime` replacement, I think the right thing to do is to maintain the standard library's conventions for the semantics and (as it seems you've done with the `in_days` and `in_hours` functions), define *extensions* that provide a more obvious and intuitive way to be explicit about the semantics you care about.

**Comment by dekoza** [comment]
Oh. My. `$DIETY`. This discussion is the exact reason why I chose `pendulum` over `datetime + dateutil + pytz` to handle my time calculations. And I'll link to it every time a time-calculation topic pops up.

The time is not about the clock. The time doesn't _care_ about the clock. What the clock _shows_ is the **consequence** of at least three factors: time passage **and** timezone information **and** DST handling (and leap seconds, yadda yadda). But no sane booking system (and I've written quite a few commercial ones during my career) uses the clock to calculate how much to charge its users. See my rent-a-car example above. When I write a booking system I want time calculations to be exact and intuitive to use. Simple operators, no jumping around. Pendulum promised all that and boy did it deliver. And I've tested **all** the datetime libraries in Python's ecosystem. Each booking system I wrote before discovering `pendulum` required ugly hacks to do The Right Thing™ at some point. I almost [started writing my own datetime library](https://xkcd.com/927/).

@pganssle I'm sorry but clearly the next thing you misunderstand is what does it actually **mean** to be a drop-in replacement. It doesn't mean to copy all mistakes and flaws. If it did then what's the point of writing a replacement in the first place? It rather means that the instance of `Pendulum` retains all attributes and methods of `datetime` instances to the point that eg. ORM can swallow it and put the correct timestamp to the db.

So thank you, @sdispater for this wonderful library.

**Comment by pganssle** [comment]
> I'm sorry but clearly the next thing you misunderstand is what does it actually mean to be a drop-in replacement.

By "drop-in replacement", I take it to mean that you can pass `pendulum` objects to functions expecting `datetime` and they should react the same way, even though functions expecting `pendulum` objects may fail if passed a `datetime` object. For the most part that means not fundamentally changing the semantics of basic pre-existing operations (even if the results you return are *also* providing drop-in replacements).

If you make this change, I suggest making it very clear in the **Limitations** section of the readme, because I suspect there is some math out there that counts on being able to do wall time semantics (recurrence rules come to mind) that will break as a result of this change. It's a particularly subtle way to break things, too.

With regards to the rest, maybe you'd be interested in learning about Chesterton's Fence.

**Comment by sdispater** [comment]
@pganssle 

> By "drop-in replacement", I take it to mean that you can pass pendulum objects to functions expecting datetime

And you can, I left the standard API methods and properties alone when subclassing the `datetime` class to avoid unexpected suprises. If this is not the case, it's a bug and you can file an issue.

And don't get me wrong here, I understand your point of view. But you have to admit that's it's far from trivial to handle DST transitions with the standard library.

I mean when I get `gettz('America/Los_Angeles')` it's because I want to work in this particular timezone and as such I also want it to respect the DST transitions that occur which the standard library does not.

This is especially true in Python 3.6 and the introduction of the `fold` attribute. This attribute has been introduced to disambiguate repeated times and yet we have this inconsistency:

```python
>>> from datetime import datetime
>>> from dateutil.tz import gettz
>>> la = gettz('America/Los_Angeles')
>>> pre_dt = datetime(2018, 11, 4, 1, 30, tzinfo=la, fold=0)
>>> post_dt = datetime(2018, 11, 4, 1, 30, tzinfo=la, fold=1)
>>> print(pre_dt)
'2018-11-04 01:30:00-07:00'
>>> print(post_dt)
'2018-11-04 01:30:00-08:00'
>>> print(post_dt - pre_dt)
'0:00:00`
```

As you can see, it should be `1:00:00`.

And, to me, the main problem is that Python is somewhat the exception regarding datetime with timezone arithmetic compared to other languages which can be really confusing for newcomers (and even for seasoned developers):

In PHP:

```php
>>> $tz = new DateTimeZone('America/Los_Angeles');
>>> $dt = new DateTime('2018-03-11 01:30', $tz);
>>> echo($dt->format('r') . "\n");
'Sun, 11 Mar 2018 01:30:00 -0800'
>>> $it = DateInterval::createFromDateString('1 hours');
>>> $dt->add($it);
>>> echo($dt->format('r') . "\n");
'Sun, 11 Mar 2018 03:30:00 -0700'
```

In Ruby:

```ruby
>>> tz = ActiveSupport::TimeZone['America/Los_Angeles']
>>> dt = tz.parse('2018-03-11T01:30:00')
>>> puts(dt)
'2018-03-11 01:30:00 -0800'
>>> puts(dt + 1.hour)
'2018-03-11 03:30:00 -0700'
```

In Go:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	dt := time.Date(2018, 3, 11, 1, 30, 0, 0, la)
	fmt.Println("", dt)
	dt_end := dt.Add(1 * time.Hour)
	fmt.Println("", dt_end)
}
```

it will output:

```
2018-03-11 01:30:00 -0800 PST
2018-03-11 03:30:00 -0700 PDT
```

And I think this is the behavior than most people expect when working in a timezone because that's the one that makes most sense.

This why I started Pendulum because neither the standard library nor the other datetime libraries out there handle it this way.
