### ISSUE TITLE
can't compare DateTime to datetime.date after upgraded to pendulum2

### ISSUE THREAD

**Issue by haoli-buaa** [sdispater/pendulum#618]
## Issue Description
Hi, my pendulum version is upgraded from 1.4.4 to 2.1.2.  I have codes that compared pendulum DateTime to datetime.date. In 1.4.4, it worked well, but in 2.1.2. It got an "TypeError: can't compare DateTime to datetime.date".

## Code Example to Reproduce
```
import pendulum, datetime
a = pendulum.now()
b = datetime.date(2022, 4, 21)
a > b
```

I am not familiar with python. Does anyone know why this comparison failed even if DateTime class in pendulum 2.1.2 inherits the Date class, which is a children class of datetime.date ? Also, is this an expected breaking change or a bug ?

**Comment by NickFabry** [comment]
First, sorry for the long delay in responding. Actually, the behavior of pendulum prior to v2.0 should probably be considered a bug - a date and a datetime are considered incomparable, and a type error should be raised if you attempt to do so.

As for why, consider what answer you should give if you are asked to compare 2020-06-10 to 2020-06-10 15:30:00. Are they equal? Certainly, the date components are. But what if 2020-06-10 represents a date to have a task completed by?And let's say the task was actually completed by 2020-06-10 15:30:00. The task was completed late, in other words, and you would probably check it with something like:

`if task_completed_datetime < due_date:
    on_time = True
else:
    on_time = False`

Or more compactly,

`on_time = (task_completed < due_date)`

So, you could reasonably argue 2020-06-10 "should be" < 2020-06-10 15:30:00. The point is, without further context, it is highly arbitrary to compare a date with a datetime - so, rather than attempt to guess, a Type exception is raised.

Note that this also happens with python's standard datetime. Try:

`import datetime
a = datetime.datetime(2020,6,10,15,30,0)
b = datetime.date(2020,6,10)
a > b
`

I hope this helps.
