### ISSUE TITLE
from_format is handling YYYY wrong

### ISSUE THREAD

**Issue by joaodlf** [sdispater/pendulum#645]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: 
- **Pendulum version**: 

## Issue

```
>>> pendulum.from_format("08/13/21", "MM/DD/YYYY").to_date_string()
'0021-08-13'
```
If anything, pendulum should be throwing an exception here.

Compare it to `datetime.strptime`:
```
>>> datetime.strptime("08/12/22", "%m/%d/%Y")
...
ValueError: time data '08/12/22' does not match format '%m/%d/%Y'
```

**Comment by Secrus** [comment]
What Pendulum version are you on?

**Comment by joaodlf** [comment]
Latest, so 2.1.2.

**Comment by WitchGod** [comment]
The question is, why are you using `MM/DD/YYYY` when the format is `MM/DD/YY`?

![image](https://user-images.githubusercontent.com/6817524/188253964-7ef915c1-98ac-4f34-ae81-f203d498ee53.png)

**Comment by joaodlf** [comment]
> The question is, why are you using `MM/DD/YYYY` when the format is `MM/DD/YY`?
> 
> ![image](https://user-images.githubusercontent.com/6817524/188253964-7ef915c1-98ac-4f34-ae81-f203d498ee53.png)

Consider that the data could be coming from user input and that we are using pendulum to validate the string format (as you could do with strptime), Pendulum should be throwing an exception, as well.

As it is, I cannot trust pendulum when it comes to external/user input. Anything that does not follow the desired format should fail.

**Comment by NickFabry** [comment]
I think that most datetime parsers are designed to follow Postel's Law: "Be conservative in what you send, be liberal in what you accept." Certainly, dateutil follows this philosophy, and it is considered very useful when parsing loosely formatted data such as dates and times. In other words, they are designed to parse, not validate. I don't think we should change that philosophy here.

But, if you want to make pendulum more strict, you can modify the source. In particular, if you look at line 153 in pendulum/formatting/formatter.py, it is:

`        "YYYY": (_MATCH_1_TO_4, _MATCH_4),
`

This is the part where pendulum decides what to do when the token 'YYYY' is encountered. I believe if you replace the tuple of choices with just a single option...

`        "YYYY": _MATCH_4,
`

...pendulum will then insist on _MATCH_4 (i.e. matching exactly four-digit integers) if you give it the token YYYY, and throw an error otherwise. I hope this helps.

**Comment by joaodlf** [comment]
I initially agreed with your assessment, but after further cosideration, I don't believe that you can separate parsing from validation. As in, those two concepts need to go hand in hand.

Parsing infers rules. Rules are meant to be followed. `YYYY` != `YY`.

After inspecting the other `_REGEX_TOKENS` elements in `pendulum/formatting/formatter.py`, I am left with even more worries. 

The documentation states:
>The next helper, from_format(), is similar to the native datetime.strptime() function but uses custom tokens to create a DateTime instance.

"Similar" can't possibly be used to describe `from_format()`. On the other hand, `datetime.strptime()` is documented like so:
> Return a string representing the date, controlled by an **explicit** format string.

Keyword here: Explicit. 

If Pendulum documents very explicit formatting tokens (`YYYY`, `YY`, `Y`), it is natural to assume a validation effort takes place.
