### ISSUE TITLE
start_of('week') and day_of_week inconsistent

### ISSUE THREAD

**Issue by blksith0** [sdispater/pendulum#683]
If today is Sunday, then **start_of('week')** will actually go back to the previous Monday.
Yet **day_of_week** will say 0.

"ISO8601 week starts on Monday"

If this is enforced then it should be consistent.
Thanks

**Comment by ndkv** [comment]
I'm also encountering this issue. 

Setting ` pendulum.week_starts_at(pendulum.SUNDAY)` and calling `start_of('week')` returns today's Sunday. 

`day_of_week()` still returns 0 which is now correct but it doesn't seem to be linked to the `pendulum.week_starts_at()` setting.

**Comment by ndkv** [comment]
I had a look at `day_of_week()`'s [definition](https://github.com/sdispater/pendulum/blob/c4e518c950bcf0a4214b36c5992ae27d3c40e47f/pendulum/date.py#L64C25-L64C25): 

```python 
    def day_of_week(self):
        """
        Returns the day of the week (0-6).

        :rtype: int
        """
        return self.isoweekday() % 7
```

and saw that it calls Python's built-in `datetime.date.isoweekday()` function which, on Python 3.10.11, returns `Monday == 1 ... Sunday == 7`:

```python
    def isoweekday(self):
        "Return day of the week, where Monday == 1 ... Sunday == 7."
        # 1-Jan-0001 is a Monday
        return self.toordinal() % 7 or 7
```

---

The issue is caused by the `% 7` in `day_of_week()` as it turns `isoweekday`'s `7` (Sunday) into `0`. 

I see two solutions

1. replace `return self.isoweekday() % 7` with `return self.isoweekday() - 1`
2. call `datetime.date.weekday()` instead as it returns `Monday == 0 ... Sunday == 6`

Which is preferable?
