### ISSUE TITLE
datetime compatibility - timestamp int vs function

### ISSUE THREAD

**Issue by numberoverzero** [sdispater/pendulum#71]
Does pendulum aim for full api compatibility with datetime.datetime?  It looks like pendulum's `timestamp` is a property, while datetime's `timestamp` is a function:

```
from datetime import datetime, timezone
import pendulum
d = datetime.now(timezone.utc)
p = pendulum.now(timezone.utc)

d.timestamp
# <function datetime.timestamp>

d.timestamp()
# 1478671704.494979

p.timestamp
# 1478671596
```

I really wanted to use pendulum under the covers and expose the interface as datetime, but this is a property I expect users to depend on having the usual signature.

**Comment by sdispater** [comment]
Thanks for pointing this out.

Yeah, pendulum's goal is to be compatible with datetime API so I'll have to change that in the next version.

**Comment by danilobellini** [comment]
That would break my code, as it uses that property and expects an int. For now, if I needed the `datetime.timestamp` method behavior, I would use the `float_timestamp` property instead.

On Python 2, `datetime` objects don't have a timestamp method. That's only available on Python 3.3+: https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp

At least, shouldn't `Pendulum` objects include a `int_timestamp` (or `seconds_since_epoch`, or `posix`, or `tstamp`) property before that backwards incompatible change, with a deprecation warning on 0.6.x users of the `timestamp` property?

**Comment by AndreasBackx** [comment]
@danilobellini the best thing then is to change your code. Pendulum should definitely remain fully compatible with Python 3's datetime module (the decision for supporting the Python 2 API is up to @sdispater). A way to keep compatibility is to create a callable float. Django has a [CallableBool](https://github.com/django/django/blob/master/django/utils/deprecation.py#L87) for the change they made `User.is_authenticated()` a property. A deprecation warning could be thrown on 0.6.x.

**Comment by pennomi** [comment]
I was just about to suggest the same thing. (You beat me to it.) That seems like the most obvious migration path.

**Comment by sdispater** [comment]
I will try to make it as smooth as possible. It won't break in `0.7.x` but I will put deprecation warnings to notify of the future breaking change.

The idea of the callable float seems like a good idea.

Anyway, in 2 major versions (`0.7` being the next) here is what will happen:

- `timestamp` will no longer be a property but a method behaving exactly like the standard library.
- `float_timestamp` will be removed.

Mean while, accessing them as properties will trigger a `DeprecationWarning`.

**Comment by danilobellini** [comment]
Using float instead of int is what will break some stuff here. Adding `()` after every `.timestamp` is a sed job, casting to int (truncating, not rounding) isn't. Ok, I'll have to migrate it, but will any int timestamp method/property remain available?

I'm not so sure about the quantization/representation loss when using comparisons with `<` (or, worse, `<=`) in the float result. The POSIX timestamp (seconds since 1970-01-01 00:00:00 UTC) has 10 digits as of today, with the microseconds it would have 16 digits, which is a digit beyond the 64 bit IEEE754 floating point representation limit (as described in page 4 here: https://people.eecs.berkeley.edu/~wkahan/ieee754status/IEEE754.PDF), unless I'm missing something (would the most significant digit being `"1"` be enough for it to be kept as lossless?). Anyway, it's not as strict as the MySQL's `from_unixtime` function and [usually] losing a microsecond digit value isn't that bad, but if microseconds were required for me, I would probably make comparisons/calculations using `(p.timestamp, p.microsecond)` or Pendulum objects directly instead of using floats.

Anyway, if float will be the new default for timestamps, will the `.end_of("day")` (and other related inputs besides `"day"`) be updated to give the last microsecond object instead of the last second?

**Comment by sdispater** [comment]
@danilobellini The promise of pendulum is to be a seamless replacement (regarding the API) to the standard library. So this issue has to be addressed to make `timestamp` a method that behaves exactly like the native one.

I will try to make it easy to migrate but eventually you will have to update your code. Now, to still get an `int` timestamp, I will see if I can find a way to make it intuitive instead of having to do `int(dt.timestamp())`. Maybe, make `timestamp()` accept an optional argument to return an int.

Regarding the `end_of()` method, you are right it should set the microseconds to `999999`.

**Comment by sdispater** [comment]
I just pushed a commit (a79cb2b111370d1cd333fc821475ef7476921b14) that addresses the issue in the following way:

```python
>>> import pendulum

>>> dt = pendulum.create(2016, 11, 10, 12, 13, 54, 589234)
>>> dt.timestamp()
1478780034.589234
>>> dt.timestamp # Still working but deprecated
1478780034
>>> dt.timestamp(True)
1478780034

# float_timestamp will now trigger a deprecation warning
>>> dt.float_timestamp
# DeprecationWarning: Pendulum.float_timestamp is deprecated.
# It will be removed in the next major version.
# Use Pendulum.timestamp() instead.
1478780034.589234
```

**Comment by danilobellini** [comment]
What do you think of `dt.timestamp.int` and `dt.timestamp.float` properties instead of a parameter? Calling with the keyword argument `as_int=True` would be explicit, but using these properties seem simpler.

The `CallableTimestamp` can include a `__str__` that shows the `DeprecationWarning` before returning the `super(CallableTimestamp, self).__str__` result.

Also, the int timestamp should return `delta.days * 86400 + delta.seconds`, where `delta` is the diff between `dt` and epoch (1970-01-01 00:00:00 UTC). Rounding from floating point won't give us trouble here as the valid `datetime.datetime` year range will always give us a timestamp with up to 12 digits, but I'd avoid floating point numbers in the internal calculations as much as possible.

**Comment by sdispater** [comment]
@danilobellini `dt.timestamp.float` and `dt.timestamp.int` are not possible since `timestamp` will eventually be a method only and not a property so you would have to change your code twice instead of once.

**Comment by danilobellini** [comment]
It's the other way around: it's possible BECAUSE `dt.timestamp` isn't a property anymore.

It shouldn't be that difficult. As you did with the `CallableTimestamp`, such instance (i.e., the "method") itself can have the 2 properties I'm describing. These aren't `dt` properties but `dt.timestamp` properties. These would be explicit about the type. The `CallableTimestamp` will eventually be a common callable, not an int, but it can keep the datetime API while keeping an explicit way to have both int and float timestamps. Or even `dt.timestamp.int()` and `dt.timestamp.float()`, it's not about the parenthesis.

I really disliked this in several ways, not only because of being something backwards incompatible. A float `timestamp` method seems hardly useful, but I see no problem in that core idea of keeping the library always datetime-compatible. Keeping the `float_timestamp` property and adding a `int_timestamp` property (or method) would be a lot better than a rounding workaround with a flag.

**Comment by sdispater** [comment]
`CallableTimestamp` is here to ease the migration and not break the API for now. It will eventually be removed.

The idea of pendulum is to be compatible with the standard library so `timestamp()` should be a method that returns a float. I don't want to make it an hybrid property (except in the case of handling a future backwards incompatibility) since it will be unintuitive and not explicit, in my opinion.

So, I will stick with the current `develop` implementation for now.

**Comment by danilobellini** [comment]
It doesn't have to be hybrid nor a singleton, though it's actually hybrid in the `develop` implementation.

Who would know that "*passing True as a parameter will truncate the result to an integer*"? The `dt.timestamp(True)` isn't explicit about it returning an `int`, and `dt.timestamp()` isn't explicit about it returning a `float`, it doesn't matter how you look to them.

Including a keyword argument makes the former `dt.timestamp` into a [slightly] bureaucratic `dt.timestamp(is_int=True)`, that is surprising when compared with both the previous Pendulum API and the datetime API, but explicit, at least. It's hybrid and dynamic (the same method returns distinct types depending on the input). Both results (the `int` and `float` ones) should be kept in the API, but now the integer timestamp is clearly secondary (there's no method with the integer result as default).

Future versions depend on possible changes on the standard `datetime.timestamp` method, should I consider Pendulum forever unstable? And it's not using semantic versioning [yet]. I really fear the `is_int` keyword name will change in future versions.

It's not about being [counter-]intuitive, it's just an issue to make the package behave "like the standard library does in Python 3.3+" that I'm complaining that shouldn't become "a move against the use of integer timestamps". People are using your library because it's not the standard library, else why would they care? Including the `int_timestamp` would be enough, I still don't know why you removed the `float_timestamp` property, but I wouldn't be using this package if it had no features beyond the standard `datetime`.

**Comment by AndreasBackx** [comment]
@danilobellini I actually am using Pendulum because it's using the original datetime API. I feel that the changes that you are suggesting isn't something that should be done by Pendulum. These very small changes are not gonna improve the library, but rather make it harder to maintain. It should be straightforward and simple.

Saying that Pendulum is unstable has no grounds. Pendulum's purpose is to be fully compatible with the datetime API and making a change to make that promise more true is what it's supposed to do.

I don't know why there should be all these kind of explicit properties added to the API. Is it that hard to round or truncate the float yourself if you really need it? Including something like `int_timestamp`  will not satisfy everyone as some people desire rounding and some desire truncating.

I completely agree with @sdispater. Please keep Pendulum a seamless replacement with an simple and extended API without too many bells and whistles.

**Comment by danilobellini** [comment]
Neither rounding nor truncating is "correct". The float itself is an approximation.

The library should provide means to easily get the exact timestamp (in both seconds and microseconds) and should have a good performance on that, because that's something any datetime library should provide. You're the one telling the library shouldn't have something, not me.

The amount of backwards incompatible changes I've seen the last few weeks is huge. That's enough for me to say it's unstable. I'm not saying backwards compatibility is "law", the bad part here is that approximations are seen as more desired than exact values, and it seems that some features may simply vanish away because of a name conflict (instead of being renamed). Should I really trust my code on this?

If the standard datetime is enough for you, I wonder why you're using this library or even typing anything here. The only reason I'm using this library is because Arrow requires casting to UTC before doing maths with time (e.g. adding a microsecond), and the datetime features aren't enough to deal with some date stuff I need. I really don't care if Pendulum includes the datetime API as its own API, but I care when anyone thinks it suffices.

**Comment by sdispater** [comment]
@danilobellini

> Who would know that "passing True as a parameter will truncate the result to an integer"? The dt.timestamp(True) isn't explicit about it returning an int, and dt.timestamp() isn't explicit about it returning a float, it doesn't matter how you look to them.

`dt.timestamp()` may not be explicit about the fact that it returns a float, but people will expect it to return a float because the standard library does.

> it's just an issue to make the package behave "like the standard library does in Python 3.3+" that I'm complaining that shouldn't become "a move against the use of integer timestamps".

There is no "move against the use of integer timestamps" since I provide a way to get it, you may not like it but it still exists.

> People are using your library because it's not the standard library, else why would they care?

It may not be the standard library but it tries to be a better version of it, and doing so it has to respect its API.

> Including the int_timestamp would be enough, I still don't know why you removed the float_timestamp property

I removed the `float_timestamp` property because it is now replaced by `timestamp()` so I don't see the point of having both of them. 

> The amount of backwards incompatible changes I've seen the last few weeks is huge.

Which ones? I'm genuinely curious because I try my best to not break the API unless there is a very good reason to (like this issue)

> That's enough for me to say it's unstable.

I never pretended otherwise. It's even written in the documentation. However, the next 0.7 version will freeze the API but as long as the `1.0` version is not released I will not consider it stable.

> it seems that some features may simply vanish away because of a name conflict (instead of being renamed)

I never removed the ability to get an integer timestamp. The way to get it is just different.

> I care when anyone thinks it suffices

When did somebody say that? If people are using pendulum it's because it provides more features than the standard library.

**Comment by danilobellini** [comment]
> When did somebody say that?

I'm reading your question as "When did somebody say [something that reveals that he/she thinks] that [having the datetime API suffices]?".

How many times it was argued that keeping the datetime API is what matters? Every complain against distinct features based on such grounds is exactly that.

> I never removed the ability to get an integer timestamp.

But I had to insist. And the solution isn't just "different". You really think that joining the two into a single method is a good idea? Some people here still didn't realize it's not a matter of rounding/truncating.

> Which ones? I'm genuinely curious because I try my best to not break the API unless there is a very good reason to (like this issue)

As an example, I'm not using the `end_of` method in my code because I knew it would change: I'm adding a day, getting its `start_of("day")` and subtracting a microsecond, exactly that. If my code was using `end_of` and adding 999999 microseconds to its result, it would be broken today. Another example: you were adding/subtracting dates like time (a day = 24 hours), now you're dealing with DST transitions properly (adding/subtracting a day might add/subtract 23 or 25 hours), but code dealing with that manually or using "days" to add/subtract multiples of "24 hours" is probably broken now. How about deprecation status of the `total_months` and `total_years`?

You can answer it yourself by running the develop test suite on the 0.6.2 release. If you change the tests that fails on 0.6.2 to pass on them, they will no longer pass on the develop branch code.

Every change breaks some code. Some yields a better library release, but it's clearly not the case of this issue.

> [...] the next 0.7 version will freeze the API [...]

No, it won't ever freeze. You will always change it to be like the datetime API, no matter what gets broken with that, and that's what it means when you say Pendulum "has to respect its API". Every new name conflict will be an issue like this one, or worse.

Every feature Pendulum has that datetime doesn't have yet should be seen as unstable, as it might be removed when datetime adds a similar feature, even if it does so using another method name.

Freezing the API isn't something good per se. I wrote before which are the bad parts.

If the datetime API include a new `posix` method/property with the integer timestamp, probably the `as_int` argument in the `Pendulum.timestamp` method will be removed. If the `datetime.timestamp` gets itself a parameter, say `epoch` (that defaults to the POSIX 1970-01-01 00:00:00 UTC), using the first positional parameter as `True` won't behave like the standard `datetime` anymore, so I doubt it would remain (though it could).

> I removed the float_timestamp property because it is now replaced by timestamp() so I don't see the point of having both of them.

Python didn't remove the `"%s" % "my string"` syntax when the new `"{0}".format("my string")` appeared. And probably Python won't ever remove that.

If you cared with backwards compatibility, the `float_timestamp` would be kept, and the obvious solution to the name conflict would be a new `int_timestamp`, so the API changes wouldn't be so surprising.

**Comment by sdispater** [comment]
> How many times it was argued that keeping the datetime API is what matters?

It matters because it's the initial promise of pendulum. I won't break this now.

> But I had to insist.

And I listened. I'm really open to discussion and suggestions. This is what we are doing right now.

> And the solution isn't just "different". You really think that joining the two into a single method is a good idea? Some people here still didn't realize it's not a matter of rounding/truncating.

It may not be a good idea but I tried to find a solution that would fix the compatibility with the standard API. So, I could add a `int_timestamp` property since `float_timestamp` will be removed and `timestamp()` now provide the same feature. And `int_timestamp`, I agree, should not be a truncation of the float timestamp.

> As an example, I'm not using the `end_of` method in my code because I knew it would change: I'm adding a day, getting its `start_of("day")` and subtracting a microsecond, exactly that. If my code was using `end_of` and adding 999999 microseconds to its result, it would be broken today.

This was clearly a bug since `end_of('month')`, for example, would properly set the microseconds to 999999 and should have been reported as such.

> Another example: you were adding/subtracting dates like time (a day = 24 hours), now you're dealing with DST transitions properly (adding/subtracting a day might add/subtract 23 or 25 hours), but code dealing with that manually or using "days" to add/subtract multiples of "24 hours" is probably broken now. How about deprecation status of the `total_months` and `total_years`?

This was also a bug so I had to fix it.

> Every change breaks some code. Some yields a better library release, but it's clearly not the case of this issue.

And that's why I still consider pendulum to be in beta right now and I put a warning on the documentation to notify this.


> No, it won't ever freeze. You will always change it to be like the datetime API, no matter what gets broken with that, and that's what it means when you say Pendulum "has to respect its API". Every new name conflict will be an issue like this one, or worse.

I don't expect the standard datetime library to change drastically in a near future (except for the fold attribute that will land in 3.6).

> Freezing the API isn't something good per se. I wrote before which are the bad parts.

I am not saying that it's necessarily a good thing but what I meant is that `0.7` will set the API for the future stable `1.0` version.

And if things needs to be backwards incompatible I will increase the version number accordingly. 

> If the datetime API include a new `posix` method/property with the integer timestamp, probably the `as_int` argument in the `Pendulum.timestamp` method will be removed. If the `datetime.timestamp` gets itself a parameter, say `epoch` (that defaults to the POSIX 1970-01-01 00:00:00 UTC), using the first positional parameter as `True` won't behave like the standard `datetime` anymore, so I doubt it would remain (though it could).

You make a good point here. That's why I am now considering the `int_timestamp` property. 

> Python didn't remove the `"%s" % "my string"` syntax when the new `"{0}".format("my string")` appeared. And probably Python won't ever remove that.

I agree. The question is, as the sole developer, how many alias I want to keep supporting.

> If you cared with backwards compatibility, the `float_timestamp` would be kept, and the obvious solution to the name conflict would be a new `int_timestamp`, so the API changes wouldn't be so surprising.

I will think about it since it's something I've already done (pendulum's own methods or properties providing the same as datetime's)

And, as a side note, I'm glad you take the time to have this discussion with me since it's important for me to have feedbacks on the library or specific points of implementation.

**Comment by numberoverzero** [comment]
First, thanks @sdispater for the fix in the develop branch.

This discussion seems to have outgrown the initial issue, which is fine.  I'd recommend capturing the outcome in a [philosophy](http://docs.python-requests.org/en/master/dev/philosophy/) or versioning section to the [changelog](https://github.com/olivierlacan/keep-a-changelog/blob/6c68f8f4077ddfb3bb4d7b31579de020bb3023db/CHANGELOG.md#change-log) (or readme, contributing guide, ...) to preserve some of the nuance here.  It will come up again, and it's far better to have a link instead of re-explaining everything.

I'll try to summarize your points, so it's easier to follow for anyone not keeping up with the thread.  Your replies have moved away from guidelines/rules and into specific examples :)

@sdispater

* API compatibility with `datetime` is very important, above nearly everything else.  This is similar to request's focus on the api, even when it violates RFCs or at the expense of security.
* Backwards incompatibility is very nearly as important, but not quite.  Deprecations should be used to help users migrate, and warn those that aren't pinning dependencies (pinning to 0.6.x would avoid user surprise if `timestamp` changed in 0.7.0)
* Correctness fixes should be expected in minor (patch during 0.x) versions (such as the end of day microseconds example) except where their complete fix (such as timestamp) would break user code in a completely unreasonable way.

@danilobellini 

* Backwards incompatibility needs to be a higher priority than it is.
  * A number of recent changes, while fixing correctness in the library, will break user code where they have explicitly worked around the bug (end of day microseconds).
  * Even though pendulum isn't "at 1.0" it's being used in production and that needs to be considered more seriously when bug fixes may break that behavior.
* How pendulum will version changes is under-defined (such as future datetime changes) and needs to be clear so users can take it into consideration when choosing pendulum.

(I'll update these if I've misunderstood either of your arguments, just let me know)

---

I think it's worth the time to define how pendulum handles versioning, where api parity with datetime falls, and maybe some example changes that fit in a minor release vs a major release.  Many of pendulum's bug fixes will be around correctness (time is hard), where we can expect a user to write their own manual fix (see @danilobellini's example for end_of) and correcting the error will re-break their fixes.

For this issue specifically, I think that means:

1. Remove the `as_int` argument from the `timestamp()` method.  This kicks the breaking change down the road since users that provide `as_int=True` will eventually break when the argument is removed.
2. Override `__add__`, `__radd__`, `__sub__`, `__bool__` and all the other [numeric magic methods](https://docs.python.org/3/library/numbers.html#module-numbers) with `DeprecationWarning`s so that `Pendulum.timestamp` has the exact same behavior for existing users, except that it raises warnings whenever someone tries to use it as an int.  For example:

    ```python
import warnings
from .version import next_minor

class CallableInt(int):
    def __init__(self, property_name, float_value):
        ...

    def __call__(self):
        return self.float_value

    def __add__(self, other):
        warnings.warn(
            "{name} will be a method in {ver}, not an int".format(
                self.property_name, next_minor()))
        return super(CallableInt, self).__add__(other)

    >>> d = pendulum.now()
    >>> d.timestamp()
    1479062805.524919
    >>> d.timestamp > 100
    __main__:1: DeprecationWarning: In 0.7.0, Pendulum.timestamp will be...
    True
    ```
3. I lost track of whether `*_timestamp` methods exist and you want to remove them, or they were a proposed fix for this issue.  If they exist and are going away, add the same warning and leave them alone until the next breaking changes.  If they don't exist, don't add them.  The callable pattern will return a float when used as a property (with warning) and an int when used as a method.  New users get the correct behavior, and existing users get a warning (but don't break).
4. Please document the version policy, including examples :) I think breaking from 0.6.x to 0.7.x is ok, as long as the rules for breaking changes are understood.  Describe the deprecation cycle -- is it warning in patch and fix in minor, or warning in minor and fix in major?

**Comment by danilobellini** [comment]
@numberoverzero wrote:
> [...] The callable pattern will return a float when used as a property (with warning) and an int when used as a method. [...]

I realize you "lost track" of what's going on, but it seems swapped. Or are you expecting an int to be returned by the method?

The method will return a float, as `datetime(...).timestamp()` would do. The method itself will be an `int` instance, actually with a type/class that inherits from `int` and implements a `__call__` so that it behaves like a "callable int" that returns a float when called. But that's temporary, in the future @sdispater wants to keep only a plain common method as the `timestamp` (maybe for using it as both `Pendulum.timestamp(dt)` and `dt.timestamp()`), so I'm talking about a definitive alternative to keep the int timestamp (exact, in seconds) available. That's where a new property like `int_timestamp` (or any other name like `posix`, `unix_timestamp` or `seconds_since_epoch`) is required, keeping the former `timestamp` property behavior.

Using the int value will [sometimes] result in a DeprecationWarning, but it seems hard to make it happen all the time, as it depends on the order you're using the operators. To do that, it probably requires not inheriting from int, so `CallableTimestamp.__radd__` would be called instead of `int.__add__` when adding (and the same with other operators). But it might not behave like an int otherwhere given such change, and I'm not sure if it's worth the trouble.

@numberoverzero wrote:
>  If they don't exist, don't add them.

C'mon, that's the opposite of what I'm saying. You proposed something whose name clashes with a property I use. I don't want it to vanish away: I want it to be better than it was.

@sdispater wrote:
> And, as a side note, I'm glad you take the time to have this discussion with me since it's important for me to have feedbacks on the library or specific points of implementation.

Thanks =) And I'm glad you're reading what I'm writing.

**Comment by numberoverzero** [comment]
Ah, thanks!  You're correct, I reversed my intent.  The code sample I provided implements what I intended (property is an int for existing code, but when called with `__call__` returns a float) but I should have said:

> [...] The callable pattern will return [an int] when used as a property (with warning) and [a float] when used as a method. [...]

I understand that this would be a temporary solution, and I'm in agreement that it should only be that.  Eventually it should just be a method that returns a float, and the acts-as-an-int interface should go away entirely.  I don't think it's actually hard to make it toss a warning all the time:

1. Override every interface for an `int` (`__add__`, `__rsub__`, etc).
2. Don't warn for `__call__`.

This is perfectly safe since an `int` is not callable, and methods don't implement `__add__`, etc.

I didn't suggest that "If they don't exist, don't add them" was your stance.  That's where I proposed a solution that doesn't break existing code, and also lines up with the datetime interface.  As far as I can tell `int_timestamp` (and a hypothetical `float_timestamp`) are extraneous.  Would `d.int_timestamp` ever return a different result from `int(d.timestamp)`?

**Comment by danilobellini** [comment]
> Would d.int_timestamp ever return a different result from int(d.timestamp)?

Yes. The float is an approximation, not the int (which should be the exact amount of seconds since epoch). You can get the float from `int_timestamp + int_microsecond * 1e-6`, but that might lose information. The obvious examples are at the higher year values, because there it happens all the time:

```python
>>> pendulum.from_timestamp(pendulum.create(9999, 10, 1, 12, 23, 11, 999992).float_timestamp)
<Pendulum [9999-10-01T12:23:12+00:00]>
>>> pendulum.from_timestamp(pendulum.create(3000, 10, 1, 12, 23, 10, 999999).float_timestamp)
<Pendulum [3000-10-01T12:23:11+00:00]>
```

When you care about microseconds, you probably want this:

```python
>>> from decimal import Decimal
>>> p = pendulum.create(3000, 10, 1, 12, 23, 11, 999998)
>>> Decimal(p.timestamp) + Decimal(p.microsecond) / 1000000
Decimal('32527311791.999998')
```

Not this:

```python
>>> p.float_timestamp
32527311791.999996
>>> p.timestamp + p.microsecond * 1e-6
32527311791.999996
```

You can get the float timestamp from the exact int timestamp and the exact microsecond value, but not the other way around. That happens because the float itself is an approximation.

**Comment by numberoverzero** [comment]
Still not sure I understand, sorry.  I can see how those are different, and that the float is an approximation.  I guess I don't see how the proposal changes the behavior at all, since pendulum [already gives you the `int_timestamp` by truncating the `float_timestamp`](https://github.com/sdispater/pendulum/blob/a4d3716bff701ac7a4990830e55a31651b0519a6/pendulum/pendulum.py#L570).  If you are getting your timestamp as an integer via `Pendulum.timestamp` then you'd get the same information from `int(Pendulum.timestamp())`.

The information is already lost because pendulum is returning a float to begin with.

**Comment by danilobellini** [comment]
The int timestamp should be fixed, not removed. I said `delta.days * 86400 + delta.seconds` before in another comment I gave to this issue. You should read before judging, unless you're really trying to be deceitful.

**Comment by numberoverzero** [comment]
I'm not trying to deceive, or judge.  I have been asking questions to try and understand the problems with my proposal, which maintains compatibility while reaching api parity.  I see now that I have not helped either cause.

My initial comment has already been addressed in the `develop` branch, and my continued involvement is not moving anything to resolution.  I'm stepping back from this discussion; there's enough passion that I know it's in the right hands.

**Comment by sdispater** [comment]
@danilobellini You are right about your examples and it's a limitation of the standard library:

```python
>>> datetime.fromtimestamp(datetime(3000, 10, 1, 12, 23, 10, 999999).timestamp())
datetime.datetime(3000, 10, 1, 12, 23, 11)
```

So, I agree, I will have to address and fix this in pendulum.

@numberoverzero pendulum will strictly follow semantic versioning from the first stable release (`1.0`)

**Comment by sdispater** [comment]
@danilobellini I can fix the integer timestamp easily. For the float timestamp, I don't think I can fix it since there is no easy way to avoid the approximation

```python
>>> 32527329790.999999
32527329791.0
```

**Comment by danilobellini** [comment]
What can be done is a decimal timestamp instead, or perhaps a tuple `(integer timestamp, microsecond value)`.

**Comment by sdispater** [comment]
Maybe. For now, I will let it behave like the standard library does since it "breaks" only for very high year value.

And the `int_timestamp` has made it to the `develop` branch :-)

It has the following implementation:

```python
delta = self._datetime - self._EPOCH

return delta.days * SECONDS_PER_DAY + delta.seconds
```
