### ISSUE TITLE
Fluent setter for weekdays?

### ISSUE THREAD

**Issue by sebasmagri** [sdispater/pendulum#87]
Hi!

Is there any way I could handle setting the weekday for a date object? It would replace the day making it match the weekday passed by the parameter (1-7) in the same week.

Regards,

**Comment by sdispater** [comment]
No, there is currently no way to do that.

The only thing you can do is set the day to the next or previous weekday:

```python
import pendulum

dt = pendulum.now()
thursday = dt.next(pendulum.THURSDAY)
```

But there is no guarantee that it will be in the same week.

**Comment by sebasmagri** [comment]
@sdispater what I'm currently doing is a small dance like this:
```
dt.start_of('week').add(days=weekday_as_0_indexed_integer)
```
Are there any issues with this approach? would it really make sense having the `weekday_` fluent helper?

**Comment by sdispater** [comment]
The only issue I see with your approach is that you lose the time information since `start_of('week')` will set the time to `00:00:00`, but if it's not an important information in your case it doesn't really matter.

As for a `weekday_()` setter, I won't add one for now, no, since it's a really specific use case that wan be worked around by using existing methods (like the the way you are doing it).

**Comment by sebasmagri** [comment]
Makes sense for me.

Closing this...

Regards,
